import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Switch PokeDex",
  description: "Generated by create next app ",
  openGraph: {
    title: "Switch PokeDex",
    description: "Generated by create next app ",
    images: [
      {
        url: "/page.jpg",
        width: 1200,
        height: 630,
        alt: "Switch PokeDex Preview",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
